import = [
  # https://github.com/catppuccin/alacritty/
  "~/.config/alacritty/catppuccin-macchiato.toml",
  "~/.config/alacritty/sonokai.toml",
]

[font]
normal.family = "JetBrainsMono Nerd Font Mono"
normal.style = "Regular"
size = 13.0

[window]
option_as_alt = "Both"
decorations = "none"
startup_mode = "Maximized"

[bell]
duration = 500
animation = "Ease"
# MacOS
command = { program = "osascript", args = ["-e", "beep"] }
# Linux 
# xkbbell
