"$schema" = 'https://starship.rs/config-schema.json'
[username]
# Disable as seems to take most time and do not use
disabled = true

[time]
disabled = false
format = '[$time](#F2CDCD) '

[git_commit]
tag_disabled = false

[shlvl]
disabled = false
format = '[$symbol]($style) '
repeat = true
symbol = '❯'
repeat_offset = 2
threshold = 0
