[[language]]
name = "fish"
formatter = { command = "fish_indent" }
auto-format = true

[[language]]
name = "bash"
indent = { tab-width = 4, unit = "\t" }
formatter = { command = "shfmt" }
auto-format = true

[[language]]
name = "html"
auto-format = false
formatter = { command = 'prettier', args = ["--parser", "html"] }

[language-server.typos]
command = "typos-lsp"

[language-server.eslint]
args = ["--stdio"]
command = "vscode-eslint-language-server"

[language-server.eslint.config]
format = { enable = true }

[language-server.eslint.config.codeAction]
disableRuleComment = { enable = true, location = "separateLine" }
showDocumentation = { enable = false }

[[language]]
name = "typescript"
auto-format = true
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
language-servers = [
  { name = "eslint", only-features = [
    "format",
    "diagnostics",
  ] },
  { name = "typos" },
  { name = "typescript-language-server", except-features = [
    "format",
  ] },
]

[[language]]
name = "markdown"
language-servers = [{ name = "marksman" }, { name = "typos" }]
formatter = { command = 'prettier', args = ["--parser", "markdown"] }

[language-server.rust-analyzer.config]
cargo.features = "all"
rust-analyzer.check.command = "clippy"
